services:
  db:
    image: postgres
    container_name: pk-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pkeeper
    ports:
      - "6500:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data

  app:
    container_name: pk-app
    build: .
    environment:
      ACCESS_TOKEN_PRIVATE_KEY_FILE: cert/jwt_key.pem
      ACCESS_TOKEN_EXPIRED_IN: 1h
      CERT_PATH: cert/server.crt
      KEY_PATH: cert/server.key
      POSTGRES_DSN: postgresql://postgres:password@pk-database:5432/pkeeper
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: ./server
volumes:
  data: